---
ID: '5c55e275-d4e4-5425-b1b8-286cfffe5775'
Parent: '00418463-bab0-55e5-9fb2-9a6ad7427657'
Template: '00418463-bab0-55e5-9fb2-9a6ad7427657'
Path: '/sitecore/templates/Project/lab/Styleguide-FieldUsage-ContentList Rendering Parameters/__Standard Values'
SharedFields:
  - ID: 'ca9b9f52-4fb0-4f87-a79f-24dea62cda65'
    Hint: __Default workflow
    Value: '{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}'
Languages:
  - Language: en
    Versions:
      - Version: 1
        Fields:
          - ID: '25bed78c-4957-4165-998a-ca1b52f67497'
            Hint: __Created
            Value: 20250203T122445Z
          - ID: '52807595-0f8f-4b20-8d2a-cb71d28c6103'
            Hint: __Owner
            Value: |
              sitecore\JssImport
          - ID: '5dd74568-4d4b-44c1-b513-0af5f4cda34f'
            Hint: __Created by
            Value: |
              sitecore\JssImport
          - ID: '8cdc337e-a112-42fb-bbb4-4143751e123f'
            Hint: __Revision
            Value: '56106d4d-dc64-43c6-b237-895d8956aca3'
          - ID: 'badd9cf9-53e0-4d0c-bcc0-2d784c282f6a'
            Hint: __Updated by
            Value: |
              sitecore\JssImport
          - ID: 'd9cf14b1-fa16-4ba6-9288-e8a174d4d522'
            Hint: __Updated
            Value: 20250203T122445Z
